apiVersion: v1
kind: Service
metadata:
  name: tomcat-test
  namespace:
  labels:
    app: tomcat-test
spec:
  ports:
  - name: "api"
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: tomcat-test
